name: Build and Release Arduino Code for Raspberry Pi Pico

permissions:
  contents: write

on:
  push:
    branches:
      - main  # mainブランチにプッシュされた時にトリガーされます
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Arduino Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1
        with:
          version: '0.31.0'

      - name: Install Raspberry Pi Pico board
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:mbed_rp2040

      - name: Compile the sketch
        run: |
          arduino-cli compile --fqbn arduino:mbed_rp2040:pico --output-dir ./build Test.ino

      - name: Upload the UF2 file to the release page
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: main
          name: Release main2
          artifacts: ./build/Test.uf2
          makeLatest: legacy
          replacesArtifacts: true
          updateOnlyUnreleased: true  # ここを true に設定
